

services:
  db:
    image: postgres:15
    container_name: mydb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data   # ✅ persist DB data
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d:ro # SQL files placed here run on first init

  app:
    build: ./backend
    container_name: backend_app
    ports:
      - "${BACKEND_APP_PORT}:${BACKEND_APP_PORT}"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - uploads_data:/app/uploads/images # Mount volume for uploaded images

  frontend:
    build: ./frontend/burrtong
    container_name: frontend_app
    ports:
      - "${FRONTEND_APP_PORT}:80"
    depends_on:
      - app

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_EXTERNAL_PORT}:${PGADMIN_INTERNAL_PORT}"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"

volumes:
  postgres_data:   # ✅ declare the volume
  pgadmin_data:
  uploads_data: # Declare the volume for uploaded images
  elasticsearch_data:
